#!/bin/sh

usage() {
    cat<<USAGE
Usage: ${0##*/} [OPTION]
options:
  -r|re <int>     Specify Re number (100, 1000, 5000, 10000)
  -c|cmake        Configure (cmake) the project first then make and run
  -h|help         print the usage
USAGE
}

error() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    usage
    exit 1
}

setRe() {
re="$1"
case $re in
  100)   col="1";;
  1000)  col="2";;
  5000)  col="3";;
  10000) col="4";;
  *)     echo "Data is not available for Re=$re" \
      && echo "Accceptable values are: 100, 1000, 5000, 10000" \
      && exit 1;;
esac
}

config=0

while [ "$#" -gt 0 ]
do
   case "$1" in
   -h | -help)
      usage && exit 0
      ;;
   -r | -re)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      setRe "$2"
      shift 2
     ;;
   --)
      shift
      break
      ;;
   -*)
      error "invalid option '$1'"
      ;;
   *)
      break
      ;;
   esac
done

[ -z "$re" ] && setRe 100
[ ! -d output ] && mkdir output

rm -f data/Central* data/residual

$(which time) -f "Elapsed=%E" python src/lidCavity.py $re

[ "$?" -eq "0" ] \
&& rm -f output/*.pdf \
&& echo "Plotting the results" \
&& python src/plotter.py $re $col
