#!/bin/bash

source ./functions

#clean the case
clean
solver=$(getSolver)
cp -r 0.orig 0

echo "Generating mesh"
foamJob -w -a blockMesh >& /dev/null

echo "Decomposition and optimizations"
foamJob -w -a decomposePar >&/dev/null
foamJob -w -a -p renumberMesh -overwrite >&/dev/null

echo "Running $solver in parallel"
foamJob -w -a -p $solver >&/dev/null

echo "Plotting validation graphs"
./plot
