#!/bin/bash
source ./functions

et="$(getValue endTime system/controlDict)"
wi="$(getValue writeInterval system/controlDict)"

[ ! -d plots/frames ] && mkdir -p plots/frames
[ ! -f foam.foam ] && touch foam.foam
rm -f plots/frames/*

PATH=$HOME/anaconda2/bin:$PATH
source activate pypv

{ python plots/video.py $et $wi;} 2>/dev/null
source deactivate
