#!/bin/bash

et="$(foamDictionary -entry endTime -value system/controlDict | tail -1)"
wi="$(foamDictionary -entry writeInterval -value system/controlDict | tail -1)"

[ ! -d plots/frames ] && mkdir -p plots/frames
[ ! -f foam.foam ] && touch foam.foam
rm -f plots/frames/*

PATH=$HOME/anaconda2/bin:$PATH
source activate pypv

{ python plots/video.py $et $wi;} 2>/dev/null
source deactivate
