#!/bin/bash
# Images from : https://arxiv.org/abs/1107.0449
# data from: https://www.sciencedirect.com/science/article/pii/0021999182900584

source ./functions

#clean the case
clean
solver=$(getSolver)

cp -r 0.orig 0
cp constant/parameters.orig constant/parameters
cp plots/horizontal_U.xy plots/horizontal_U_old.xy
cp plots/vertical_U.xy plots/vertical_U_old.xy

echo "Generating mesh"
foamJob -w -a blockMesh >& /dev/null

echo "Renumbering Matrices"
foamJob -w -a renumberMesh -overwrite >&/dev/null

echo "Running $solver"
foamJob -w -a $solver >&/dev/null

echo "Plotting validation graphs"
./plot
