#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

foamJob -w -a foamCleanTutorials
foamJob -w -a blockMesh
#foamJob -w -a decomposePar
$(which time) -f "Elapsed=%E" foamJob -w -a -p $application

if [ "$?" -eq "0" ]; then
    iter=$(tac log | grep -m1 "SIMPLE" | grep -o "[0-9]*\.[0-9]*")
    
    if [ ! -z "$iter" ]; then
        dt=$(foamDictionary -entry dt -value constant/parameters)
        iter=$(python -c "print(int($iter/$dt))")
        echo "Converged after $iter iterations."
    else
        echo "More iterations are required"
    fi
    
    rm -f plots/*.pdf
    echo "Plotting the results"
    ./plot
else
    echo "Solution diverged!"
fi
#------------------------------------------------------------------------------
