#!/bin/sh
gnuplot<<EOF
    set terminal pdf enhanced color
    set output "plots/cd.pdf"
    set xlabel "Time (s)"
    set ylabel "C_d"
    set title  "Drag coefficient"
    set grid
    set key right bottom

    plot [1:][] "postProcessing/forceCoeffs/0/forceCoeffs.dat" u 1:3 w l notitle
EOF

gnuplot<<EOF
    set terminal pdf enhanced color
    set output "plots/cl.pdf"
    set xlabel "Time (s)"
    set ylabel "C_l"
    set title  "Lift coefficient"
    set grid
    set key right bottom

    plot [0:][] "postProcessing/forceCoeffs/0/forceCoeffs.dat" u 1:4 w l notitle
EOF
