#!/bin/sh

case $re in
  100)   col="2";;
  1000)  col="3";;
  5000)  col="4";;
  10000) col="5";;
  *)     echo "Data is not available for Re=$re" \
      && echo "Accceptable values are: 100, 1000, 5000, 10000" \
      && exit 1;;
esac

gnuplot<<EOF
    set terminal pdf enhanced color
    set output "plots/uvelocity.pdf"
    set ylabel "y (m)"
    set xlabel "U_x (m/s)"
    set title  "Velocity fluctuations at the middle in x-dir. with Re=$re"
    set grid
    set key right bottom

    plot "postProcessing/singleGraph/2/vertical_U.xy" u 2:1 t "Numerical" w l, \
         "plots/yu" u $col:(\$1*0.1) w p ls 26 t "Ghia"
EOF

gnuplot<<EOF
    set terminal pdf enhanced color
    set output "plots/vvelocity.pdf"
    set xlabel "x (m)"
    set ylabel "U_y (m/s)"
    set title  "Velocity fluctuations at the middle in y-dir. with Re=$re"
    set grid
    set key top right

    plot "postProcessing/singleGraph/2/horizontal_U.xy" u 1:3 t "Numerical" w l , \
         "plots/xv" u (\$1*0.1):$col w p ls 26 t "Ghia"
EOF
