#!/bin/sh
re=$(foamDictionary -entry re -value constant/parameters)
case $re in
  100)   col="2";;
  1000)  col="3";;
  5000)  col="4";;
  10000) col="5";;
  *)     echo "Data is not available for Re=$re" \
      && echo "Accceptable values are: 100, 1000, 5000, 10000" \
      && exit 1;;
esac

#lt=$(foamListTimes -latestTime -processor | tail -1)
lt=$(foamListTimes -latestTime | tail -1)

cp postProcessing/singleGraph/$lt/horizontal_U.xy plots/
cp postProcessing/singleGraph/$lt/vertical_U.xy plots/

gnuplot<<EOF
    set terminal pdf enhanced color
    set output "plots/uvelocity.pdf"
    set ylabel "y (m)"
    set xlabel "x (m)"
    set y2label "U_x (m)" tc lt 2
    set x2label "U_y (m)"
    set y2range [-0.5:0.5]
    set x2range [-1:1]
    set title  "Velocity fluctuations at the middle for Re=$re"
    set grid
    set key out top
    set size square
    
    plot "plots/vertical_U.xy" u 2:1 t "Numerical, U_x" w l  axes x2y1, \
         "plots/yu" u $col:1 w p ls 4 t "Ghia, U_x"  axes x2y1, \
         "plots/horizontal_U.xy" u 1:3 t "Numerical, U_y" w l  axes x1y2, \
         "plots/xv" u 1:$col w p ls 2 t "Ghia, U_y" axes x1y2
EOF

