#!/bin/bash

[ -z $1 ] && nd='2' || nd="$1"

proj=${PWD##*/}
lt=$(foamListTimes -latestTime)

div=$(awk 'BEGIN { print '"$lt/$nd"'}')
st=($(seq 0 $div $lt))

touch ${proj}.foam

if [ "$(hostname)" == "cfd-lab" ]; then
  export BK=$PATH
  export PATH=/home/taher/anaconda/anaconda2/bin:$PATH
else
  source activate pvpy
  export PYTHONPATH=$HOME/.conda/envs/pvpy/lib/python2.7/site-packages/paraview/vtk:$PYTHONPATH
fi

echo "Plotting the data using Paraview"

for i in $(seq 0 $(expr ${#st[@]} - 2)); do
    [ "$i" != "${#st[@]}" ] \
    && python plots/render.py $proj ${st[$i]} ${st[$(expr $i + 1  )]} &
done

wait

if [ "$(hostname)" == "cfd-lab" ]; then
  unset PATH
  export PATH=$BK
else
  source deactivate
  unset PYTHONPATH
fi

fn=$(foamListTimes -withZero | wc -l)
fr=$(expr $fn / $lt)

rm -f plots/3DRender.mp4
if [ "$(hostname)" == "cfd-lab" ]; then
  ffmpeg -r $fr -f image2 -s 1530x790 -i plots/frames/final.%03d.png \
  -vcodec libx265 -crf 25  -pix_fmt yuv420p plots/3DRender.mp4
else
  foamCreateVideo -d plots/frames/ -i final -o plots/3DRender -fps $fr
fi
